# Generated by Django 5.0.6 on 2024-07-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_kind_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
