# Generated by Django 5.0.6 on 2024-07-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_couserseold_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
    ]
