# Generated by Django 5.0.6 on 2024-07-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
